{
 "title": "Automatisk Egenkontrol - AAK",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "department",
    "label": "Afdeling",
    "query": "SELECT DISTINCT department \nFROM \"mtaarhus-kommune\".\"etrefrigerator-sensor\"\nWHERE department != 'Jesper Torvekøkken'\nORDER BY department;\n"
   },
   {
    "name": "sensorID",
    "label": "Vælg køle/fryseskab(e)",
    "query": "SELECT \nname AS \"__value\", \nappliance || ' (' || \n  CASE \n    WHEN floor IS NULL THEN room || ', Etage ukendt'\n    WHEN room = floor THEN room\n    ELSE floor || ', ' || room\n  END || ')' AS \"__text\"\nFROM \"mtaarhus-kommune\".\"etrefrigerator-sensor\"\nWHERE department = '$department'\nORDER BY appliance, floor, room;\n"
   },
   {
    "name": "Uge",
    "query": "SELECT DISTINCT \n    CONCAT(DATE_PART('year', time_index), '-', LPAD(DATE_PART('week', time_index)::TEXT, 2, '0')) AS week\nFROM \"mtaarhus-kommune\".\"etrefrigerator-sensor\"\nWHERE $__timeFilter(time_index)\n  AND time_index IS NOT NULL\nORDER BY week;\n"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <h1><strong>KØLESKABE</strong></h1>\r\n \r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <h1><strong>FRYSERE</strong></h1>\r\n \r\n</div>"
   }
  },
  {
   "title": "Graf (Køleskabe)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time_index AS \"time\",\r\n  CONCAT(floor, ' - ', room, ' - ', appliance) AS Metric,\r\n  temperature\r\nFROM \"mtaarhus-kommune\".\"etrefrigerator-sensor\"\r\nWHERE\r\n  $__timeFilter(time_index) \r\n  AND department IN ('$department') \r\n  AND name IN ($sensorID)\r\n  AND (\r\n    LOWER(appliance) LIKE '%køl%' \r\n    OR LOWER(appliance) LIKE '%frugt%' \r\n    OR LOWER(appliance) LIKE '%grønt%'\r\n  )  -- Filter to include \"køl\", \"frugt\", and \"grønt\"\r\nORDER BY 1, 2;\r\n"
    },
    { "dataset": "quantumleap" }
   ]
  },
  {
   "title": "Graf (Frysere)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time_index AS \"time\",\r\n  CONCAT(floor, ' - ', room, ' - ', appliance) AS Metric,\r\n  temperature\r\nFROM \"mtaarhus-kommune\".\"etrefrigerator-sensor\"\r\nWHERE\r\n  $__timeFilter(time_index) AND department IN ('$department') \r\n  AND name IN ($sensorID) \r\n  AND LOWER(appliance) LIKE '%frys%'\r\n  AND time_index BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\nORDER BY 1, 2;\r\n"
    }
   ]
  },
  {
   "title": "Seneste temperaturmåling(køleskabe)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH latest_per_entity AS (\r\n  SELECT DISTINCT ON (entity_id)\r\n    entity_id,\r\n    floor, room, appliance,\r\n    temperature,\r\n    time_index\r\n  FROM \"mtaarhus-kommune\".\"etrefrigerator-sensor\"\r\n  WHERE\r\n    $__timeFilter(time_index)\r\n    AND department IN ('$department')\r\n    AND name IN ($sensorID)\r\n    AND (\r\n      lower(appliance) LIKE '%køl%' OR lower(appliance) LIKE '%koel%' OR lower(appliance) LIKE '%kol%'\r\n      OR lower(appliance) LIKE '%frugt%'\r\n      OR lower(appliance) LIKE '%grønt%' OR lower(appliance) LIKE '%groent%'\r\n    )\r\n  ORDER BY\r\n    entity_id,\r\n    time_index DESC                 -- newest row per entity_id\r\n),\r\nlatest_entity_per_location AS (\r\n  SELECT DISTINCT ON (floor, room, appliance)\r\n    entity_id,\r\n    floor, room, appliance,\r\n    temperature,\r\n    time_index\r\n  FROM latest_per_entity\r\n  ORDER BY\r\n    floor, room, appliance,\r\n    time_index DESC                 -- newest entity (by last seen time) for that combo\r\n)\r\nSELECT\r\n  CONCAT(floor, ' - ', room, ' - ', appliance) AS \"sammenkædning\",\r\n  ROUND(temperature::numeric, 1)               AS value\r\nFROM latest_entity_per_location\r\nORDER BY \"sammenkædning\";\r\n"
    }
   ]
  },
  {
   "title": "Seneste temperaturmåling(frysere)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH latest_per_entity AS (\r\n  SELECT DISTINCT ON (entity_id)\r\n    entity_id,\r\n    floor, room, appliance,\r\n    temperature,\r\n    time_index\r\n  FROM \"mtaarhus-kommune\".\"etrefrigerator-sensor\"\r\n  WHERE\r\n    $__timeFilter(time_index)\r\n    AND department IN ('$department')\r\n    AND name IN ($sensorID)\r\n    AND LOWER(appliance) LIKE '%fry%'   -- only freezers\r\n  ORDER BY\r\n    entity_id,\r\n    time_index DESC                     -- newest row per entity_id\r\n),\r\nlatest_entity_per_location AS (\r\n  SELECT DISTINCT ON (floor, room, appliance)\r\n    entity_id,\r\n    floor, room, appliance,\r\n    temperature,\r\n    time_index\r\n  FROM latest_per_entity\r\n  ORDER BY\r\n    floor, room, appliance,\r\n    time_index DESC                     -- newest entity (by last seen time) for that combo\r\n)\r\nSELECT\r\n  CONCAT(floor, ' - ', room, ' - ', appliance) AS \"Værdi\",\r\n  ROUND(temperature::numeric, 1)               AS value\r\nFROM latest_entity_per_location\r\nORDER BY \"Værdi\";"
    }
   ]
  },
  {
   "title": "Gennemsnitlige køleskabstemperaturmåling for den valgte uge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CONCAT(floor, ' - ', room, ' - ', appliance) AS metric,\r\n  AVG(temperature) AS value\r\nFROM \"mtaarhus-kommune\".\"etrefrigerator-sensor\"\r\nWHERE\r\n  department IN ('$department') \r\n  AND name IN ($sensorID)\r\n  AND DATE_PART('week', time_index) = CAST(SPLIT_PART('$Uge', '-', 2) AS INTEGER) -- Extract the week number\r\n  AND DATE_PART('year', time_index) = CAST(SPLIT_PART('$Uge', '-', 1) AS INTEGER) -- Filter by year\r\n  AND appliance IS NOT NULL -- Exclude appliances that are NULL\r\n  AND (\r\n    LOWER(appliance) LIKE '%køl%' \r\n    OR LOWER(appliance) LIKE '%frugt%' \r\n    OR LOWER(appliance) LIKE '%grønt%'\r\n  ) -- Include \"køl\", \"frugt\", and \"grønt\"\r\nGROUP BY metric\r\nORDER BY 1, 2;\r\n"
    }
   ]
  },
  {
   "title": "Gennemsnitlige frysertemperaturmåling for den valgte uge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  CONCAT(floor, ' - ', room, ' - ', appliance) AS \"Værdi\",\r\n  AVG(temperature) AS value \r\nFROM \r\n  \"mtaarhus-kommune\".\"etrefrigerator-sensor\"\r\nWHERE \r\n  name IN ($sensorID)\r\n  AND DATE_PART('week', time_index) = CAST(SPLIT_PART('$Uge', '-', 2) AS INTEGER) -- Extract the week number\r\n  AND DATE_PART('year', time_index) = CAST(SPLIT_PART('$Uge', '-', 1) AS INTEGER) -- Filter by year\r\n  AND appliance IS NOT NULL -- Exclude appliances that are NULL\r\n  AND LOWER(appliance) LIKE '%fry%' -- Filter for refrigerators\r\n  AND time_index BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\nGROUP BY \r\n  floor, room, appliance -- Group by all columns used in CONCAT\r\nORDER BY \r\n  floor, room, appliance;\r\n"
    }
   ]
  },
  { "title": "Gennemsnitlig uge temperatur", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  { "type": "library-panel-ref", "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 } }
 ]
}